import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import MessageInput from "@/app/components/MessageInput";
import { MessageListContextProvider } from "./contexts/MessageContext";
import { library } from '@fortawesome/fontawesome-svg-core'
import { fas } from '@fortawesome/free-solid-svg-icons'

library.add(fas)

const poppins = Poppins({ subsets: ["latin"], weight: ['300', '700'] });

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${poppins.className} flex flex-col justify-between min-h-screen`}>
        <MessageListContextProvider>
          <Header />
            {children}
          <MessageInput />
        </MessageListContextProvider>
      </body>
    </html>
  );
}
